import type { Metadata } from "next";
import { LegalPageLayout, LegalSection } from "@/app/components/LegalPageLayout";

export const metadata: Metadata = {
  title: "Terms & Conditions — FxInsites",
};

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms &amp; Conditions" updated="September 8, 2026">
      <LegalSection title="Acceptance of these terms">
        <p>
          By creating an account or using FxInsites, you agree to these terms. If you don&apos;t
          agree, please don&apos;t use the service.
        </p>
      </LegalSection>

      <LegalSection title="What FxInsites is">
        <p>
          FxInsites is a trade planning, backtesting, and journaling tool. It structures the trade
          ideas you provide and checks them against general risk-management principles.{" "}
          <strong className="text-zinc-200">
            FxInsites does not provide financial advice and does not generate trade signals.
          </strong>{" "}
          Nothing on this site should be taken as a recommendation to buy, sell, or hold any
          financial instrument.
        </p>
      </LegalSection>

      <LegalSection title="Not financial advice, no guaranteed results">
        <p>
          Trading involves substantial risk of loss and is not suitable for everyone. Backtest
          results are based on historical data and do not guarantee future performance. You are
          solely responsible for your own trading decisions and their outcomes.
        </p>
      </LegalSection>

      <LegalSection title="AI-generated content">
        <p>
          Trade plans are generated by an AI model based on the information you provide. They may
          contain errors, omissions, or inaccuracies. Always independently verify a plan before
          acting on it.
        </p>
      </LegalSection>

      <LegalSection title="Your account">
        <p>
          You&apos;re responsible for keeping your login credentials secure and for all activity
          that happens under your account. Let us know right away if you suspect unauthorized
          access.
        </p>
      </LegalSection>

      <LegalSection title="Subscriptions and billing">
        <p>
          Paid plans are billed through Paystack according to the pricing and usage limits shown on
          our pricing page. You can cancel your subscription at any time from your account;
          cancellation takes effect at the end of your current billing period. Fees already paid are
          non-refundable except where required by law.
        </p>
      </LegalSection>

      <LegalSection title="Acceptable use">
        <p>You agree not to:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>Attempt to circumvent rate limits or usage caps.</li>
          <li>Resell or provide access to the service to others without our agreement.</li>
          <li>Submit unlawful, abusive, or infringing content through the planner.</li>
          <li>Attempt to disrupt, reverse-engineer, or gain unauthorized access to the service.</li>
        </ul>
      </LegalSection>

      <LegalSection title="Intellectual property">
        <p>
          The FxInsites name, design, and underlying software are owned by the operator of this
          service. Nothing in these terms transfers ownership of that to you.
        </p>
      </LegalSection>

      <LegalSection title="Disclaimer and limitation of liability">
        <p>
          FxInsites is provided &quot;as is&quot;, without warranties of any kind. To the maximum
          extent permitted by law, the operator of FxInsites is not liable for trading losses or any
          other damages arising from your use of the service.
        </p>
      </LegalSection>

      <LegalSection title="Termination">
        <p>
          We may suspend or terminate an account that violates these terms, or misuses the service.
        </p>
      </LegalSection>

      <LegalSection title="Governing law">
        <p>
          These terms are governed by the laws of South Africa, without regard to conflict-of-law
          principles, except where local consumer-protection law requires otherwise.
        </p>
      </LegalSection>

      <LegalSection title="Changes to these terms">
        <p>
          We may update these terms from time to time. Changes will be posted on this page with an
          updated date at the top.
        </p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>
          Questions about these terms? Email{" "}
          <a href="mailto:hello@fxinsites.com" className="text-sky-400 hover:text-sky-300">
            hello@fxinsites.com
          </a>
          .
        </p>
      </LegalSection>
    </LegalPageLayout>
  );
}
